const certificateData = [
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
    {
      name: "Nzurum Vanessa . C",
      regNumber: "SD2024/SC/001",
      email: "Vanessanzurum@gmail.com",
      stack: "full stack",
      result: "80%",
      status: "issued",
    },
  ];

  export default certificateData;